#!/bin/bash
set -ex

KIND_CLUSTER_NAME=skind-cluster
reg_name='kind-registry'
reg_port='5000'

cli_help() {
  cli_name=${0##*/}
  echo "
skind [Simple Kubernetes In Docker]
Version: 0.0.1
https://github.com/famartinrh/skind
Usage: $cli_name [command]
Commands:
  start    Starts an opinionated Kind cluster
  stop     Stops the Kind cluster
  status   Prints information about the current running cluster
  expose   Create Ingress for exposing a Service
  *        Help
"
  exit 1
}

start() {
  echo "Starting..."

  if [ $(kind get clusters | grep ${KIND_CLUSTER_NAME} | wc -l) = 1 ]
  then
    echo "Cluster already exists"
  else

    # create registry container unless it already exists
    running="$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)"
    if [ "${running}" != 'true' ]; then
      echo "Creating image registry"
      docker run -d --restart=always -p "${reg_port}:5000" --name "${reg_name}" registry:2
    fi

    echo "Creating Cluster..."

    # create a cluster with the local registry enabled in containerd
    tmpkindconfig=$(mktemp /tmp/tmpkindconfig.XXXXXX)
    echo "
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins.\"io.containerd.grpc.v1.cri\".registry.mirrors.\"localhost:5000\"]
    endpoint = [\"http://kind-registry:5000\"]
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: \"ingress-ready=true\"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker" >> $tmpkindconfig

    echo "using kind config"
    cat $tmpkindconfig

    kind create cluster --name ${KIND_CLUSTER_NAME} --config=$tmpkindconfig
    rm "$tmpkindconfig"

    # connect the registry to the cluster network
    docker network connect "kind" "${reg_name}" || true

    # tell https://tilt.dev to use the registry
    # https://docs.tilt.dev/choosing_clusters.html#discovering-the-registry
    for node in $(kind get nodes --name $KIND_CLUSTER_NAME); do
      kubectl annotate node "${node}" "kind.x-k8s.io/registry=localhost:${reg_port}";
    done

    # setup ingress
    # using nginx ingress
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
    kubectl patch deployment ingress-nginx-controller -n ingress-nginx --type=json -p '[{"op":"add","path":"/spec/template/spec/containers/0/args/-","value":"--enable-ssl-passthrough"}]'
    kubectl rollout status -n ingress-nginx deployment/ingress-nginx-controller

    echo "skind cluster started"
  fi
}

stop() {
  echo "Stopping..."
  kind delete cluster --name $KIND_CLUSTER_NAME

  running="$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)"
  if [ "${running}" == 'true' ]; then
    echo "Deleting image registry"
    containerID="$(docker inspect -f '{{.Id}}' "${reg_name}" )"
    docker stop "${containerID}"
    docker rm "${containerID}"
  fi
}

status() {
  if [ $(kind get clusters | grep ${KIND_CLUSTER_NAME} | wc -l) = 1 ]
  then
    echo "Cluster is running"
    kubectl version
    kubectl get namespaces
  else
    echo "Cluster is not running"
  fi
}

expose() {
  svcname=$1

  if [ "$svcname" == "" ]; then
    echo "missing service name as first argument"
    exit 1
  fi

  svcport=$(kubectl get service $svcname -o=jsonpath={.spec.ports[0].port})

  if [ "$svcport" == "" ]; then
    echo "error getting service port from kubernetes, does the service $svcname exists?"
    exit 1
  fi

  echo "Creating ingress for service $svcname using port $svcport in current namespace"

  tmpingressconfig=$(mktemp /tmp/tmpingressconfig.XXXXXX)
  echo "
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $svcname-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: $svcname.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: $svcname
                port:
                  number: $svcport" >> $tmpingressconfig

  cat $tmpingressconfig

  kubectl apply -f $tmpingressconfig
  rm $tmpingressconfig

}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  expose)
    expose $2
    ;;
  *)
    cli_help
    ;;
esac